namespace Oblikovati.API;

public enum AngularPrecisionEnum {
	kZeroDecimalPlaceAngularPrecision,
	kOneDecimalPlaceAngularPrecision,
	kTwoDecimalPlacesAngularPrecision,
	kThreeDecimalPlacesAngularPrecision,
	kFourDecimalPlacesAngularPrecision,
	kFiveDecimalPlacesAngularPrecision,
	kSixDecimalPlacesAngularPrecision,
	kSevenDecimalPlacesAngularPrecision,
	kEightDecimalPlacesAngularPrecision,
	kDegreesAngularPrecision,
	kMinutesAngularPrecision,
	kSecondsAngularPrecision,
	kSecondsOneDecimalPlaceAngularPrecision,
	kSecondsTwoDecimalPlaceAngularPrecision,
	kSecondsThreeDecimalPlaceAngularPrecision,
	kSecondsFourDecimalPlaceAngularPrecision,
}
