namespace Oblikovati.API;

public enum ProfileDirectionTypeEnum {
	kPerpendicularToThePredominantDirection,
	kParallelToThePredominantDirection,
	kCircularToTheCenterOfTheSurfaceToWhichTheSymbolApplies,
	kAtADefinedAngleToThePredominantDirection,
}
